---
- hosts: new_nodes
  gather_facts: yes
  become: yes
  roles:
  - rhsm-timeout
  - role: atomic-update
    when: openshift.common.is_atomic

- hosts: new_nodes
  gather_facts: no
  become: yes
  serial: 1
  roles:
  - role: rhel_subscribe
    when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and rhel_subscription_user is defined
  - role: rhsm-subscription
    when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and rhsm_user is defined

- hosts: new_nodes
  gather_facts: no
  become: yes
  roles:
    - rhsm-repos
    - prerequisites
    - { role: docker-storage-setup, docker_dev: "/dev/xvdb", docker_vg: "docker_vg", docker_data_size: "95%VG", docker_dm_basesize: "3G" }
    - { role: docker, default_docker_storage_block_device: "/dev/xvdb", default_docker_storage_volume_group: "docker_vg" }
  when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
        ansible_distribution == "RedHat" and (rhsm_user is defined or repo_mirror_url is defined)
