---
- hosts: new_nodes
  gather_facts: yes
  become: yes
  serial: 1
  roles:
    - aws-rhsm-subscription

- hosts: new_nodes
  gather_facts: no
  become: yes
  roles:
    - rhsm-repos
    - prerequisites
    - { role: docker-storage-setup, docker_dev: "/dev/xvdb", docker_vg: "docker_vg", docker_data_size: "95%VG", docker_dm_basesize: "3G" }
    - { role: docker, default_docker_storage_block_device: "/dev/xvdb", default_docker_storage_volume_group: "docker_vg" }
