---
- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  serial: 1
  roles:
  - role: aws-rhsm-subscription
    when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and rhel_subscription_user is not defined

- hosts: cluster_hosts
  gather_facts: no
  become: yes
  roles:
  - role: rhsm-repos
    when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and rhel_subscription_user is not defined
  - prerequisites
  - { role: docker-storage-setup, docker_dev: "/dev/xvdb", docker_vg: "docker_vg", docker_data_size: "95%VG", docker_dm_basesize: "3G" }
  - { role: docker, default_docker_storage_block_device: "/dev/xvdb", default_docker_storage_volume_group: "docker_vg" }

- hosts: master
  gather_facts: no
  become: yes
  roles:
  - master-prerequisites
